### ISSUE TITLE
Proposal for Spring Framework

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#15]
Working with the JDBC API can be redundant. Especially when processing exceptions, preparing and executing statements, opening connections, and more.

With the [Spring JDBC Framework](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html#jdbc-introduction) we can eliminate all of the redundant code and save time.

We may also benefit from Spring's [Web Framework](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html) which features support for uploading files.

**Comment by MichaelTavener** [comment]
I 100% support this. Spring has a bit of a learning curve but overall its going to save you time all over the place.  

Side note: If you set this up correctly, you _should_ be able to change databases by only changing a class name in a config file. That's not a requirement but is certainly something worth knowing about Spring.

**Comment by lb-cake** [comment]
It's settled. Spring will be used.
