### ISSUE TITLE
Create authentication module

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#20]
This module/servlet will take a username from a web parameter and store it in a user's session for future use.

Example: http://localhost/deploya?username=Bob

**Comment by MichaelTavener** [comment]
This module/servlet can probably be combined with the actual upload functionality.

**Comment by JonathanKessler** [comment]
I would suggest keeping them separate. It would make it easier to replace the authentication module in the future should the need arise.
