### ISSUE TITLE
Research format for communicating to the REST interface

### ISSUE THREAD

**Issue by kesslerk** [VarenTechInternship/varentech-deploya#26]

**Comment by MichaelTavener** [comment]
You won't necessarily have a "format" per se, but you will have to plan out the REST api.

Example:
- GET http://your.app/users <-- returns a list of users.
- GET http://your.app/users/:id <-- where id is the id of a user, should return info on just that user.
- DELETE http://your.app/users/:id  <-- where id is the id of a user to remove
- POST http://your.app/users <-- body of the message would have data for a new user, probably json formatted.

Not that there is any need at all to have a user management system or anything like that. These are just examples for how a rest interface would work.

**Comment by kesslerk** [comment]
If these are not necessary, in what ways should we use REST?

We have:
GET http://localhost:8080/home/login <-- gets username from the user
POST http://localhost:8080/home/upload <-- returns all data they enter in the html form

**Comment by MichaelTavener** [comment]
Those are legit! Additional stuff you might want:
GET http://localhost:8080/history <-- return a list of all uploads and the info about each upload (who ran it, what ran it, when did it run, what was the command used, was it successful, and anything else you think might be useful) Tossing it back in json would be awesome.

**Comment by kesslerk** [comment]
We began working on this but we are concerned there will be too much data displayed on the screen. Is there a way you want us to cut this down? Or is this not a problem?
