### ISSUE TITLE
Research Typesafe Config

### ISSUE THREAD

**Issue by kesslerk** [VarenTechInternship/varentech-deploya#27]
Research and create a configuration file

**Comment by mraynor** [comment]
Also decide what things we would like to set in this file.

**Comment by lb-cake** [comment]
First off, the hooray emojis are great.

Second, maybe have the database be configurable?

**Comment by lb-cake** [comment]
Number of tables, table names, columns, column names be configurable?

**Comment by MichaelTavener** [comment]
> Number of tables, table names, columns, column names be configurable?

Naw, none of that needs to be configurable, those should all be static.

Example configurable stuff:
- Port the user interface will run on.
- Title to display on the gui

Stuff like that.
