### ISSUE TITLE
Using Mockito

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#34]
The internet loves Mockito! Let's find out how we can use Mockito to help us with our project. According to the official website, it allows us to create very readable tests and produce clean verification errors. 

Obviously, I want to make our tests not only useful, but easy to understand. 
@MichaelTavener @JonathanKessler , have either of you two used this in a project, and how has it been beneficial for you?

**Comment by JonathanKessler** [comment]
The internet loves Mockito for good reason and I use it frequently when unit testing. It's not just the ability to create readable tests and producing clean verification errors. It allows you to make pure unit tests where you're only testing what you actually care about testing by mocking other objects.

For example, let's say you had a method within a class that depended on a member of that class. Your unit of work, or method, relies on that member's method doing something. You don't necessarily know or care how it works. It may not be in a state to give you the answer you want or you may not have what you need to properly construct it. And if you were to go to the trouble of constructing it properly and getting it in the right state you would essentially be testing all of that code as well as your method and that's really not what you want to do. Hence Mockito. You say mock this object and when you call this method with this argument, return this value. I don't care about anything else (Please note the below may not be perfect, I typed it in notepad on my laptop that has no ide):

```
public TestClass {
    private RandomClass randomClass;

    public TestClass(RandomClass randomClass) {
        this.randomClass = randomClass;
    }

    public int methodWeWantToTest() {
        return randomClass.someMethod() * 2;
    }
}

@Test
public void testMethodWeWantToTest() {
    RandomClass mockRandomClass = mock(RandomClass.class);
    when(mockRandomClass.someMethod()).thenReturn(17);

    TestClass testClass = new TestClass(mockRandomClass);
    assert(testClass.methodWeWantToTest() == 34);
}
```

Another mocking library I use when I am testing code that relies on communicating with a web server or rest endpoints is called WireMock. It essentially stands up a fake web server for your unit tests. Similar to mockito, you tell it what endpoints to listen to, on what ports, protocols, etc and then what response to provide. I would focus on Mockito first as you'll be using that much more.

**Comment by MichaelTavener** [comment]
I've never used Mockito before. Howeva, I will say that JUnit is probably what you will encounter the most so you should get some experience with it.

**Comment by JonathanKessler** [comment]
Mockito is typically used within JUnit testing, not in place of it. Tav you really ought to look into it. It's incredibly useful.

**Comment by MichaelTavener** [comment]
Sell it to me in two sentences :p
