### ISSUE TITLE
General design

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#4]
Brainstorm and collaborate on a general design for the application as a whole. This ticket will serve as a parent ticket. As classes, packages or modules begin to be defined, we will generate design tickets for each of them attached to this ticket.

**Comment by kesslerk** [comment]
We talked about some general ideas and came up with some questions. Our idea is that we would have a place where the user can upload their jar files. When the user initially accesses the app we will get the "Who" component and add the jars to a queue. When we take the jar files off the queue we will see whether or not the jar file is executable. If the jar is not executable, we will get the "When" and the "What" will be that the file was not executed. If the jar is executable, we will execute it and get the "When" and the "What".

Our questions:

How do we know if a jar file is executable or not?
When the jar is executed, is there any feedback from the command line? If so, how do we make sense of it?
What changes are we tracking for the "What"? 
How do we know what changes were made to the program?
Do the jar files have unique names or do we need to create a unique id?

**Comment by JonathanKessler** [comment]
The jar file may not be executable. When a user uploads the jar, or tar, they will also need to be able to provide a location where that file should be placed, instructions on how to unpack it (optionally), and exactly what command to use to run the program.

There is no way to know ahead of time if the execution will produce any output. If it does, you do not have to make sense of it. You simply have to save it somewhere (within the dB).

Tav and I need to get a comprehensive list of the what together for you and will do so on the wiki soon, preferably tonight.

Changes to files and the contents of the archives can be tracked by looking at a hash of the file. At least, that will tell you if the files changed but won't show you the actual changes. You wouldn't be able to see those in compiled code so that's not something we would expect you to track. However maintaining a copy of the files themselves slmewhere and being able to associate that saved copy with the information you track about it would allow a user to exa.ine them manually at a later time.

Jar files are not guaranteed to have unique names.

Jon Kessler
Varen Technologies

**Comment by kesslerk** [comment]
We added a general layout to the Design branch

**Comment by MichaelTavener** [comment]
> How do we know if a jar file is executable or not?

Concur with Jon, you won't know. And you don't have to care.

> When the jar is executed, is there any feedback from the command line? If so, how do we make sense of it?

Same as before, don't worry about feed back of any kind of whatever it is the user uploaded. This is an app designed to be used by developers, not a huge swathe of general public. So if they uploaded a package that doesn't work it's on them.  Not to mention that when trying to submit something like a Storm topology the "submit" stage will provide feedback and will get pretty upset if it didnt like the archive. Anyhoo, this step is unimportant and we can worry about it later.

> What changes are we tracking for the "What"? 
> How do we know what changes were made to the program?

Compute the MD5 checksum for all packages being uploaded. If the bits are the same you get the same hash output from MD5 so you would be 100% sure a new package was being uploaded. But on this note, you don't necessarily need to worry about this. We are less concerned that the user uploaded a new jar/package that has changes and more concerned about tracking the fact that it was uploaded at all.

> Do the jar files have unique names or do we need to create a unique id?

These files will not have a unique name. Some web libraries will automatically throw a unique id on an upload. However, if the lib you guys use doesnt I would recommend renaming every file to something like this: originalname-user-timestamp. Or, maybe better, you need to store a row in the db for the fact that this file was uploaded. After the intert, get the id of the new row and attach that to the filename. If the id is the primary key (and it should be) it will be guaranteed to be unique in your app space.
