### ISSUE TITLE
Look into RPM

### ISSUE THREAD

**Issue by mraynor** [VarenTechInternship/varentech-deploya#48]

**Comment by mraynor** [comment]
RPM is a package manager. So I think we will package our program as an RPM? 
I created a directory for this, which includes directories for SPECS and SOUCRES. Inside the SPECS directory i created a .spec file that contains  information about the program, such as the name, version, a summary, sources, build requirements, a description, and a few others.
It also has:
- The %prep script - the first script RPM executes during a build.
-  The %install script - do whatever is necessary to actually install the newly built software.
- The %doc directive - flag the filename(s) that follow, as being documentation
- The %config directive -  used to flag the specified file as being a configuration file

**Comment by JonathanKessler** [comment]
That is correct, when building the project with maven you will have the option to package it as an rpm. It is great that you have begun to create and understand a spec file and the directory structure that rpm requires because it is important to understand how it all works. However as this is a maven project I'd suggest using the maven rpm plugin to accomplish this.

**Comment by MichaelTavener** [comment]
An RPM is cool, but please allow the distribution of this application _without_ an RPM as well.  You need to root access to install RPMs and that is generally not something that's easy to get. Requiring root access to install the app would bar its usage on a great many systems.

**Comment by lb-cake** [comment]
Currently looking into making our project an executable Jar and an RPM with the Codehaus Mojo Maven plugin.
1. Primary Maven goal is to make the executable Jar
2. Secondary Maven goal is to make the RPM.

**Comment by annoytheworld93** [comment]
Uber Jar has been created with Maven Shade plugin. ^

**Comment by mraynor** [comment]
I made a second profile for packaging as a rpm. The code is in the Embedded-Jetty-Jsp branch. It creates a folder and creates the specs, sources, rpms, build, etc. We are unsure what else needs to be done in order to finish this off, especially with mappings, etc.

**Comment by mraynor** [comment]
We made an rpm that when installed, can run the jar from a script (./script) and IT WORKS! ☻
