### ISSUE TITLE
Hashing of each individual file in an archive file.

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#49]
This should be be a simple Python script that: 
1. Takes the stdout from a process as the Python script argument.
2. Loop through and read it line by line.
3. Creates a new File type object for each line. (Each line is a file.)
4. Read the byte code of the file and take the hash of that.

**Comment by JonathanKessler** [comment]
I like it. I was thinking the other night this would be a good opportunity to write a python script since the bash was getting a bit complicated. I suggest considering having your script produce its output in json format to make it easy to read and parse within deploya.

**Comment by MichaelTavener** [comment]
Please make the functionality surrounding the Python dependency optional.  For instance, if the app is deployed on a system without Python installed this functionality should simply be disabled without preventing the usage of the app's other features.

**Comment by lb-cake** [comment]
Okay. From what I have gathered when it comes to hashing individual files, I can only find a way to first unpack that archived file then, once unpacked, I can get the md5 hash of each individual file. For now, out of @MichaelTavener's request, I will be doing this in Java. It may be an expensive operation, but I'd like to make this now, then optimize it later if need be. 

So what I'm doing:
1. Getting the file from the web app.
2. With this file, getting the hash value of the compressed file.
3. Creating a temporary directory.
4. Finding the extension type and creating a new process that unpacks it to this temporary directory.
5. Calling upon our hashing class and looping through this temporary directory and finding the md5 hash of each individual file.
6. Storing this file in our database.
7. Deleting our temporary directory.

**Comment by lb-cake** [comment]
Katie and I have worked on this, and it should almost be done...
