### ISSUE TITLE
App skeleton

### ISSUE THREAD

**Issue by MichaelTavener** [VarenTechInternship/varentech-deploya#5]
Setup an initial app skeleton and commit it to the repo. We know that we are using java and we know that we are using maven. A pom file that builds a "hello world" executable java app is acceptable for this.

**Comment by kesslerk** [comment]
I added an updated pom and an app skeleton with empty methods.

**Comment by MichaelTavener** [comment]
If it compiles then you can close this ticket. Just looking for a starting point.
