### ISSUE TITLE
History Page

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#50]
This history page should produce two pages:
## Page One:

Everything in the Entries Table.
1. id
2. username
3. file_name
4. time_stamp
5. path_to_local_file
6. path_to_destination
7. unpack_args
8. execute_args
9. archive
## Page Two:

Everything in the Entries_Details Table:
1.  id
2. entries_id
3. file_name
4. hash_value
5. output
6. error

**Comment by annoytheworld93** [comment]
Done! Now to make it pretty...

**Comment by lb-cake** [comment]
Done, now to make it pretty...
