### ISSUE TITLE
Change hardcoded "localhost" in URLs to dynamic hostname

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#56]
This software won't necessarily be installed on the end user's local machine. It could reside on a server somewhere that they access remotely. Therefore anywhere in the codebase there is a redirect to "localhost" it should be changed to whatever the hostname is which you can probably obtain from the HttpServletRequest object.

Here's one example that I found:

https://github.com/VarenTechInternship/varentech-deploya/blob/ServerTry6372/src/main/java/com/varentech/deploya/Form/LoginServlet.java#L49

**Comment by mraynor** [comment]
This is done!
