### ISSUE TITLE
Make timeout for task execution configurable

### ISSUE THREAD

**Issue by JonathanKessler** [VarenTechInternship/varentech-deploya#57]
I'd make the timeout for task execution configurable and I'd also suggest setting the default to something larger like 10 minutes. There should also be an option for no timeout (as in the program just plain runs until it exits on its own or dies). I suggest using a value of -1 for that option.

https://github.com/VarenTechInternship/varentech-deploya/blob/ServerTry6372/src/main/java/com/varentech/deploya/Form/ProcessFile.java#L79

**Comment by kesslerk** [comment]
This is done!
