### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MichaelTavener** [VarenTechInternship/varentech-deploya#60]
The README.md states that to run the app I must: 

> Execute the jar file and go to the login page..

yet the following does not work;

``` bash
$ ./deploya-1.0-SNAPSHOT.jar
./deploya-1.0-SNAPSHOT.jar: line 1: $'PK\003\004': command not found
./deploya-1.0-SNAPSHOT.jar: line 2: $'\237\335H': command not found
K-*▒▒ϳR0▒3▒▒r,J▒▒,K-▒▒V▒+▒▒▒J3sJt▒*▒B▒▒▒▒r▒-▒Z▒▒RKRS▒2▒♣▒▒↓▒: No such file or directory
./deploya-1.0-SNAPSHOT.jar: line 4: $'\276\211e\251y': command not found
./deploya-1.0-SNAPSHOT.jar: line 5: syntax error near unexpected token `)'
./deploya-1.0-SNAPSHOT.jar: line 5: `▒z▒z▒►})▒^)▒ ▒,▒▒-▒x▒x▒PK♥♦'
```

nor does

``` bash
$ java -cp com.varentech.deploya.Driver -jar deploya-1.0-SNAPSHOT.jar
no main manifest attribute, in deploya-1.0-SNAPSHOT.jar
```

Please provide more detailed quick start instructions in the README.

**Comment by MichaelTavener** [comment]
I hear the jar works now.  The readme, and this ticket, can probably be updated.

**Comment by mraynor** [comment]
We updated the README in the Ebedded-Jetty-Jsp branch, which is where the jar currently works.

**Comment by MichaelTavener** [comment]
If the goal of that branch is complete, go ahead and merge it into develop.
