### ISSUE TITLE
Code format cleanup

### ISSUE THREAD

**Issue by kesslerk** [VarenTechInternship/varentech-deploya#63]

**Comment by lb-cake** [comment]
Hey @MichaelTavener , we are a bit at a standstill. When I add code I like to have 2 spaces instead of the default 4, which eventually creates different styles in our code when we update it. It is ultimately your tool. Would you have a preference on this matter?

We are currently looking at lines that exceed 80 characters, and if it's excessive, we are refactoring it.

**Comment by JonathanKessler** [comment]
Generally speaking it doesn't matter whether you use 2 or 4 spaces, whether you put curly braces at the end of a line when starting a block of code or on the next line, etc. It is however good to be consistent throughout a codebase. I recommend coming to a consensus on these various style points as a team (and if @MichaelTavener  has opinions I'm sure can/has chime in). There is a maven checkstyle plugin that you can use to ensure you haven't missed anything once you get it configured. And wouldn't you know it there is an intellij check style plugin that uses the same config file as the maven checkstyle plugin. That will make formatting issues show up in your ide to make it even easier to "fix".

**Comment by MichaelTavener** [comment]
I highly highly recommend using the checkstyle plugin that Jon recommended.  I honestly have not seen two spaces for indentation outside of a few shell scripts.  One option you have is to mandate that tabs be used for indentation (and put that in your checkstyle config) but you @annoytheworld93 can configure tabs to be displayed at 2 spaces and everyone else can set them to display at 4, or even 8. Then everyone is happy!  The main priority is absolutely consistency. Find something everyone agrees on a roll with it.

**Comment by MichaelTavener** [comment]
Status of this? If you peeps are regularly using checkstyle plugins before commits I think you can close this.
