### ISSUE TITLE
Correctly Package as a jar

### ISSUE THREAD

**Issue by mraynor** [VarenTechInternship/varentech-deploya#71]

**Comment by mraynor** [comment]
Initially the jsps were not in the jar at all. So i added them, but they still do not open in the web browser. When i execute the jar I get "No Spring WebApplicationInitializer types detected on classpath" and I don't know if this is an actual problem or just a warning?

**Comment by mraynor** [comment]
I know this is a lot ( and possibly unhelpful), but I turned debugging on, and all of this (and more) popped up once I executed the jar and tried to open up the login page

`14:38:53.385 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@5f34b300{r=1,c=false,a=DISPATCHED,uri=/ProjectThunder/login.jsp} action REQUEST_DISPATCH 
14:38:53.387 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.eclipse.jetty.server.Server - REQUEST /ProjectThunder/login.jsp on HttpChannelOverHttp@5f34b300{r=1,c=false,a=DISPATCHED,uri=/ProjectThunder/login.jsp} 
14:38:53.387 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.j.server.handler.ContextHandler - scope null||/ProjectThunder/login.jsp @ o.e.j.w.WebAppContext@6fb554cc{/ProjectThunder,file:/home/admin/IdeaProjects/InternApp/target/src/main/webapp,AVAILABLE} 
14:38:53.388 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.j.server.handler.ContextHandler - context=/ProjectThunder||/login.jsp @ o.e.j.w.WebAppContext@6fb554cc{/ProjectThunder,file:/home/admin/IdeaProjects/InternApp/target/src/main/webapp,AVAILABLE} 
14:38:53.400 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.eclipse.jetty.server.session - sessionManager=org.eclipse.jetty.server.session.HashSessionManager@4cb2c100 
14:38:53.400 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.eclipse.jetty.server.session - session=null 
14:38:53.401 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.jetty.servlet.ServletHandler - servlet /ProjectThunder|/login.jsp|null -> jsp@19c47==org.eclipse.jetty.jsp.JettyJspServlet,0,true 
14:38:53.404 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.jetty.servlet.ServletHandler - chain=null 
14:38:53.406 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet - JspEngine --> /login.jsp 
14:38:53.407 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet -         ServletPath: /login.jsp 
14:38:53.407 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet -            PathInfo: null 
14:38:53.428 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet -            RealPath: /home/admin/IdeaProjects/InternApp/target/src/main/webapp/login.jsp 
14:38:53.428 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet -          RequestURI: /ProjectThunder/login.jsp 
14:38:53.428 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG org.apache.jasper.servlet.JspServlet -         QueryString: null 
14:38:53.444 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@25164f85[PROCESSING][i=ResponseInfo{HTTP/1.1 404 /ProjectThunder/login.jsp,340,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@19103285] generate: NEED_HEADER (null,[p=0,l=340,c=4096,r=340],true)@START 
14:38:53.446 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@25164f85[PROCESSING][i=ResponseInfo{HTTP/1.1 404 /ProjectThunder/login.jsp,340,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@19103285] generate: FLUSH ([p=0,l=226,c=8192,r=226],[p=0,l=340,c=4096,r=340],true)@COMPLETING 
14:38:53.446 {qtp1595212853-11 - /ProjectThunder/login.jsp} DEBUG`

**Comment by JonathanKessler** [comment]
I found this link, it may provide some insight:

http://stackoverflow.com/questions/22938689/info-no-spring-webapplicationinitializer-types-detected-on-classpath

**Comment by MichaelTavener** [comment]
Fixed the "build as uber jar" part of this ticket under #73. However, I did not do anything with the missing jsps :)

**Comment by kesslerk** [comment]
We can now package our project as an uber jar that can serve our jsp files. The problem now is that the jsp files are not processing the java code. Instead, the java code is displayed on the jsp web page.
![screenshot 1](https://cloud.githubusercontent.com/assets/19536917/16963405/5208dbde-4dc4-11e6-89d4-217fc8e8693a.png)

**Comment by kesslerk** [comment]
In the Package branch, the jsps are in the jar but we get this.
![screenshot 2](https://cloud.githubusercontent.com/assets/19536917/17175384/43eff250-53d5-11e6-95de-584920256db4.png)

In the packageJar branch, the jsps display but without processing the java code as shown above.

**Comment by MichaelTavener** [comment]
https://github.com/jetty-project/embedded-jetty-jsp/blob/master/src/main/java/org/eclipse/jetty/demo/Main.java  <-- give that a look over. It seems to do quite a bit with telling the context how to handle jsps.

**Comment by mraynor** [comment]
I made a branch called Embedded-Jetty-Jsp, it serves the jsps on the web page, but it does not access the database. Do we package the database in the jar or is it somewhere else?

**Comment by MichaelTavener** [comment]
You guys nailed it in ticket #84.  You want to create the database the first time the app runs if it doesnt already exist. It certainly sounds like you can close this ticket!
