### ISSUE TITLE
Web App Layout

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#8]
What is the layout for our web app? What will the client see on the website? What sort of technologies must we implement in order to make this as simple as possible?

**Comment by MichaelTavener** [comment]
My suggestion for a "tech" is [bootstrap](http://getbootstrap.com/). I wouldn't really look at it as a tech stack or anything like that, it is really a pile of prebuild css styles and some helper logic that will allow you to quickly throw together some good looking web pages without a lot of effort.

As for the backend libs, I have no idea. I've never implemented a java web app without an application server like tomcat so you are blazing new territory, at least to me. I guess my only piece of advice here is if you have several techs to choose from, go for the simplest / most straight forward one.
