### ISSUE TITLE
Initial Database Checks

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#84]
When deploya.jar first runs, it must do the following:
1. Check the config file to see if the path to the database exists.
2. If the path to the database does not lead to a SQLite db, then create a default db. As well as the necessary tables.
3. If the path provides a necessary db, then establish a connection with that db.

**Comment by lb-cake** [comment]
Committed some changes to External-Config-File branch.

**Comment by mraynor** [comment]
All of these checks are done. We are working on pushing these to develop.

**Comment by kesslerk** [comment]
This is merged to develop
