### ISSUE TITLE
Uploading files to the servlet.

### ISSUE THREAD

**Issue by lb-cake** [VarenTechInternship/varentech-deploya#9]
I think this can be done with Tomcat, an example is shown in the top comments.

[Check this.](http://stackoverflow.com/questions/2422468/how-to-upload-files-to-server-using-jsp-servlet)

**Comment by MichaelTavener** [comment]
Yup definitely can be done with tomcat.  And tomcat would make this task suuuuuuuuuuper easy.  But unless you can embed tomcat in a single jar (I doubt it but I'm not saying that's impossble, I haven't looked) it's not exactly the fit we are going for.

**Comment by JonathanKessler** [comment]
A quick google shows that Tomcat can be embedded and can be packaged in an uber jar with the rest of the app. I'm not advocating it mind you, just saying that it is possible.

**Comment by MichaelTavener** [comment]
Well then tomcat is still on the table! I really just want this thing as easy as possible to deploy all over the place.

**Comment by lb-cake** [comment]
Collectively, we have decided to go with Jetty for this one, mostly because we want to make this as light-weight as possible.
