### ISSUE TITLE
Authentication via http headers

### ISSUE THREAD

**Issue by MichaelTavener** [VarenTechInternship/varentech-deploya#91]
Allow users to bypass the login page if an http header has been set for their username.  This would allow authentication to be performed by another service, such as a proxy.

Headers are passed like key value pairs. The header could be of the form "auth-username" => "tavusername". The exact key to use for this header should be specified in the config file. "auth-username" is acceptable as a default header key to look for.

**Comment by kesslerk** [comment]
How could we test whether or not we successfully got the header? Can we set a header without a proxy?

**Comment by kesslerk** [comment]
String userName = request.getHeader(default_header);
if(userName!=null){
        session.setAttribute("Username", userName);
        response.sendRedirect("http://" + request.getServerName() + ":" + port + context_path + "/form.jsp");
    }

Would request.getHeader("auth-username"); get us the http header you are talking about?

**Comment by MichaelTavener** [comment]
> Would request.getHeader("auth-username"); get us the http header you are talking about?

I'm fairly certain that would do it.  As for testing it I believe there are chrome extensions that allow you to craft http requests, headers included.

**Comment by MichaelTavener** [comment]
I went ahead and wrote a [quick nodejs app](https://github.com/VarenTechInternship/requesta) to help you guys test this functionality. Instructions are in the readme.

**Comment by kesslerk** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/19536917/17775642/2e37bb7e-6527-11e6-8024-2d9671210658.png)
We ran our app and then ran your app and got this error.

**Comment by MichaelTavener** [comment]
Hey the redirect thing actually sounds like it might be doing what you want. Try it with a bad header and see if the same issue arises.

**Comment by kesslerk** [comment]
It works! Thank you.
